[gcp_primary]
gcp-main ansible_host=34.47.91.153 tunnel_token=eyJhIjoiYWUwY2EzNGM0NzRmNzI0NGE1ZjQ3ODg1M2QzOGE0NzYiLCJ0IjoiN2VkODE5Y2ItMzc2NS00MGIyLTk3YWUtZGFjNTYyMDg3MDg4IiwicyI6ImVsbEpUa2hXZVU0eGJXd3phWGhtZEdOQ2ExaFNaMVUwVFV0bGVqVmxhSGs9In0= db_conn=chilseongpa-project:asia-northeast3:hybrid-primary-db

[gcp_monitoring]
gcp-monitor ansible_host=34.50.24.199 tunnel_token=eyJhIjoiYWUwY2EzNGM0NzRmNzI0NGE1ZjQ3ODg1M2QzOGE0NzYiLCJ0IjoiNThkOTI0MTktYjgwMi00ZjgyLWI0M2QtZGI1MTQ4ZjRhM2ZjIiwicyI6IldHNWlhMHhUUkRJNVptNXFObXRtV0VoR1l6VmplVzlrYlhCck0zbEZUWG89In0=

[aws_bastion]
aws-bastion ansible_host=13.124.99.88

[aws_nodes]
aws-sub ansible_host=10.20.2.194 tunnel_token=eyJhIjoiYWUwY2EzNGM0NzRmNzI0NGE1ZjQ3ODg1M2QzOGE0NzYiLCJ0IjoiYzYwM2MxMTktOGJjOS00ZTViLTkxZWItNDA1YjU5NTFhMzE0IiwicyI6Ik0wTTBhVUpxY0ZWaFYzWk1OalpIWldjNU4yUjRiR05QYjFBNGJtcFBkbWM9In0=

# --- 그룹별 변수 설정 ---

[gcp_primary:vars]
ansible_ssh_private_key_file=~/.ssh/id_ed25519

[gcp_monitoring:vars]
ansible_ssh_private_key_file=~/.ssh/id_ed25519
storage_setup_enabled=false

[aws_bastion:vars]
ansible_ssh_private_key_file=../../chilseong-jh.pem

[aws_nodes:vars]
ansible_ssh_private_key_file=../../chilseong-jh.pem
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ubuntu@13.124.99.88 -i ../../chilseong-jh.pem -o StrictHostKeyChecking=no"'

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_user=ubuntu
gcp_project_id=chilseongpa-project
cf_client_id=a83c943c83dd064490dbd9b06fee3f63.access
cf_client_secret=e2de0b5838a9fffebaaf0588d4bdb770b5625e7477e730833a649a69a1738c66
aws_ip=10.20.2.194
gcp_ip=34.47.91.153
gcp_internal_ip=10.30.0.2
app_domain=app.hjh-dev.site
grafana_domain=grafana.hjh-dev.site
prometheus_domain=prometheus.hjh-dev.site
db_instance_name=chilseongpa-project:asia-northeast3:hybrid-primary-db
