[gcp_primary]
gcp-main ansible_host=34.50.41.150 tunnel_token=eyJhIjoiYzg1YTI4NDJiY2M0NDZlMmE2NmY2Y2ZkODk4MjU3OTAiLCJ0IjoiN2ZkN2RhZDctZTg5MC00YjdlLWI2MWItY2M0MDQ0NGQ4YjU5IiwicyI6IlJrMVNSVEl6ZVVGSlJHbGxZa1pQVTNOTU0wZGtWMWxHYVcxeFVXVk9ZM2c9In0= db_conn=chilseongpa:asia-northeast3:hybrid-primary-db

[aws_bastion]
aws-bastion ansible_host=43.203.128.137

[aws_nodes]
aws-sub ansible_host=52.78.116.70 tunnel_token=eyJhIjoiYzg1YTI4NDJiY2M0NDZlMmE2NmY2Y2ZkODk4MjU3OTAiLCJ0IjoiNTY0ZjMzNjItYTAxYS00MzlkLTk5NzEtZDYxNDk0ZDEyZDdkIiwicyI6IlFrMXRSWHBrU1RCMU9UaHFjR2hoYUhKWU0zWnJSamxSWTA1d1oyMHdOMWs9In0=
aws-monitor ansible_host=10.20.1.139 tunnel_token=eyJhIjoiYzg1YTI4NDJiY2M0NDZlMmE2NmY2Y2ZkODk4MjU3OTAiLCJ0IjoiNWMyY2M0YjYtZGQ3Yy00MjUzLWJiNWMtMjIwZjhkYTVjZDY0IiwicyI6IlNWVmpabVJSVEVaYVdtSkliMUZpVGpOWlZ6RjZPRTFIUm1sdllUaFZTRlE9In0=

# --- 그룹별 변수 설정 ---

[gcp_primary:vars]
# 앤서블 실행 위치(infra/ansible) 기준 두 단계 위
ansible_ssh_private_key_file=../../my_gcp_key

[aws_bastion:vars]
ansible_ssh_private_key_file=../../chilseongpa_keypair.pem

[aws_nodes:vars]
ansible_ssh_private_key_file=../../chilseongpa_keypair.pem
# 💡 핵심: Monitoring 등 내부망 서버 접속을 위해 Bastion을 징검다리로 사용
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ubuntu@43.203.128.137 -i ../../chilseongpa_keypair.pem -o StrictHostKeyChecking=no"'

[all:vars]
ansible_user=ubuntu
gcp_project_id="chilseongpa"
cf_client_id="a94b92aff485ba5410e20a8757a4d980.access"
cf_client_secret="fa27bcbd269a28685c9db04c3efa80624030da5dc8dd3137044be1509ff36266"