# 0. GCP 설정
gcp_project_id: "{{ lookup('env', 'TF_VAR_gcp_project_id') }}"

# 1. 모니터링 관련 기본 설정
storage_setup_enabled: true # EBS 볼륨을 사용할지 여부 (true/false) false 면 로컬, true 면 EBS 볼륨 사용
ebs_device_name: "/dev/nvme1n1"
monitoring_base_dir: "/home/ubuntu/monitoring"


# 2. 템플릿 경로 설정 (tasks/main.yml에서 사용)
prometheus_config_src: "prometheus.yml.j2"
alertmanager_config_src: "alertmanager.yml.j2"
alert_rules_src: "alert.rules.yml.j2"
grafana_datasource_src: "datasource.yml.j2"
grafana_dashboard_provider_src: "dashboard.yml.j2"
config_render_mode: "template"





# 4. 알림 설정
alert_webhook_url: "http://alert-bot:5000/webhook"


# 디스코드 개발자 포털에서 가져온 값들
discord_bot_token: "{{ lookup('env', 'DISCORD_BOT_TOKEN') }}"
discord_channel_id: "123456789012345678" # 알림을 받을 채널 ID

# 구글 AI 스튜디오에서 가져온 값
gemini_api_key: "{{ lookup('env', 'GEMINI_API_KEY') }}"