# 1. 도메인 및 기본 정보
app_domain: "app.bucheongoyangijanggun.com"          # 유저님의 실제 도메인
monitoring_domain : "status.bucheongoyangijanggun.com" # 모니터링용 서브 도메인
monitoring_base_dir: "/home/ubuntu/monitoring"

# 2. 클라우드플레어 인증 (테라폼 아웃풋 값)
cf_client_id: "{{ lookup('env', 'CF_CLIENT_ID') }}"
cf_client_secret: "{{ lookup('env', 'CF_CLIENT_SECRET') }}"

# 3. 템플릿 경로 설정 (tasks/main.yml에서 사용)
prometheus_config_src: "prometheus.yml.j2"
alertmanager_config_src: "alertmanager.yml.j2"
alert_rules_src: "alert.rules.yml.j2"
grafana_datasource_src: "datasource.yml.j2"
grafana_dashboard_provider_src: "dashboard.yml.j2"
config_render_mode: "template"




# 4. 저장소 설정
storage_setup_enabled: false

# 5. 알림 설정
alert_webhook_url: "http://alert-bot:5000/webhook"