# 1. 도메인 및 기본 정보
app_domain: "app.bucheongoyangijanggun.com"          # 유저님의 실제 도메인
monitoring_domain : "status.bucheongoyangijanggun.com" # 모니터링용 서브 도메인
monitoring_base_dir: "/home/ubuntu/monitoring"

# 2. 클라우드플레어 인증 (테라폼 아웃풋 값) 
# inventory.ini에 정의된 변수명과 일치
cf_client_id: "{{ cf_id }}"         
cf_client_secret: "{{ cf_secret }}"

# 3. 템플릿 경로 설정 (tasks/main.yml에서 사용)
prometheus_config_src: "prometheus.yml.j2"
alertmanager_config_src: "alertmanager.yml.j2"
alert_rules_src: "alert.rules.yml.j2"
grafana_datasource_src: "datasource.yml.j2"
grafana_dashboard_provider_src: "dashboard.yml.j2"
config_render_mode: "template"




# 4. 저장소 설정
storage_setup_enabled: false

# 5. 알림 설정
alert_webhook_url: "http://alert-bot:5000/webhook"


# 디스코드 개발자 포털에서 가져온 값들
discord_bot_token: "{{ lookup('env', 'DISCORD_BOT_TOKEN') }}"
discord_channel_id: "123456789012345678" # 알림을 받을 채널 ID

# 구글 AI 스튜디오에서 가져온 값
gemini_api_key: "{{ lookup('env', 'GEMINI_API_KEY') }}"